before_script:
    - date
    - uname -a
    - printenv | sort

gcc:
    image: gpdowning/gcc
    script:
    - ls -al
    - cat makefile
    - make versions
    - make run > /dev/null 2>&1
    - make test
    - make check
      #    - make tests
